apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: user
    version: v1
  name: user
  namespace: dhcims-msapoc-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
        version: v1
    spec:
      containers:
        - name: user
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: ORACLE_USER
              valueFrom:
                secretKeyRef:
                  name: user-oracle
                  key: user
            - name: ORACLE_PWD
              valueFrom:
                secretKeyRef:
                  name: user-oracle
                  key: pwd
          image: <image-name>
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 400m
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 512Mi
          volumeMounts:
            - mountPath: /opt/webserver/lib/application.properties
              name: application-config
              subPath: application.properties
            - mountPath: /opt/webserver/lib/logback.xml
              name: logs-config
              subPath: logback.xml
            - mountPath: /app-logs
              name: logs-dir
      volumes:
        - configMap:
            items:
              - key: application.properties
                path: application.properties
            name: user-config
          name: application-config
        - configMap:
            items:
              - key: logback.xml
                path: logback.xml
            name: user-logs
          name: logs-config
        - name: logs-dir
          emptyDir: {}